<!--<form class="form-horizontal">
  <div class="form-group">
    <label for="inputEmail3" class="col-sm-2 control-label">Email</label>
    <div class="col-sm-6">
      <input type="email" class="form-control" id="inputEmail3" placeholder="Email">
    </div>
  </div>

  <div class="form-group">
    <label for="inputPassword3" class="col-sm-2 control-label">Password</label>
    <div class="col-sm-6">
      <input type="password" class="form-control" id="inputPassword3" placeholder="Password">
    </div>
  </div>

  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-6">
      <div class="checkbox">
        <label>
          <input type="checkbox"> Remember me
        </label>
      </div>
    </div>
  </div>
  <div class="form-group">
    <div class="col-sm-offset-2 col-sm-10">
      <button type="submit" class="btn btn-default">Sign in</button>
    </div>
  </div>
</form>-->
<div class="radio">
  <label class="radio-inline">
    <input type="radio" name="radioButton" value="individual" onclick="verificaPessoa(this.value);"> Pessoa Física
  </label>
  <label class="radio-inline">
    <input type="radio" name="radioButton" value="company" onclick="verificaPessoa(this.value);"> Pessoa Jurídica
  </label>
</div>




<!--OS CAMPOS PARA CADASTRO DA PESSOA FÍSICA-->
<div id="individual" style="display:none;">AQUI FICAM OS CAMPOS DA PESSOA FISICA</div>
<!--OS CAMPOS PARA CADASTRO DE PESSOA JURÍDICA-->
<div id="company" style="display:none;">AQUI FICAM OS CAMPOS DA PESSOA JURIDICA</div>

<script src="<?php echo JS; ?>/main.js"></script>
