-- MySQL Script generated by MySQL Workbench
-- 08/23/16 22:41:01
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema projeto
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `projeto` DEFAULT CHARACTER SET utf8 ;
USE `projeto` ;

-- -----------------------------------------------------
-- Table `projeto`.`enderecos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`enderecos` (
  `idEndereco` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(150) NOT NULL,
  `numero` VARCHAR(5) NOT NULL,
  `complemento` VARCHAR(150) NOT NULL,
  `bairro` VARCHAR(50) NOT NULL,
  `cep` VARCHAR(10) NOT NULL,
  `cidade` VARCHAR(50) NOT NULL,
  `estado` VARCHAR(15) NOT NULL,
  `uf` CHAR(2) NOT NULL,
  PRIMARY KEY (`idEndereco`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`pessoas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`pessoas` (
  `idPessoa` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(100) NOT NULL,
  `telefone` VARCHAR(14) NOT NULL,
  `email` VARCHAR(100) NOT NULL,
  `username` VARCHAR(50) NOT NULL,
  `senha` VARCHAR(50) NOT NULL,
  `idEndereco` INT NOT NULL,
  PRIMARY KEY (`idPessoa`, `idEndereco`),
  INDEX `enderecos_idEndereco_idx` (`idEndereco` ASC),
  CONSTRAINT `enderecos_idEndereco`
    FOREIGN KEY (`idEndereco`)
    REFERENCES `projeto`.`enderecos` (`idEndereco`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `projeto`.`pessoasFisicas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `projeto`.`pessoasFisicas` (
  `idpessoasFisicas` INT NOT NULL AUTO_INCREMENT,
  `cpf` VARCHAR(11) NOT NULL,
  `sexo` TINYINT(1) NOT NULL,
  `idPessoa` INT NOT NULL,
  PRIMARY KEY (`idpessoasFisicas`, `idPessoa`),
  INDEX `pessoas_idPessoa_idx` (`idPessoa` ASC),
  CONSTRAINT `pessoas_idPessoa`
    FOREIGN KEY (`idPessoa`)
    REFERENCES `projeto`.`pessoas` (`idPessoa`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
